name: styled_logger
description: A package for making styled logging. Supports bolding, verbose, warning/error colors, and more.
version: 1.0.0
repository: https://github.com/Calebh101/styled_logger

environment:
  sdk: ^3.8.1

dependencies:
  web: ^1.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
